version: '3.5'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: 'conference-bot'
    env_file: 
      - '.env'
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:8080
    volumes:
      - ./src:/app/src